### ISSUE TITLE
SMTP Protocol

### ISSUE THREAD

**Issue by mhenden** [axllent/silverstripe-enquiry-page#13]
We were wondering if there was a way to use this form with SMTP authentication? Can't see anything in the documentation or in the backend configuration screens. Because of the lack of AMTP authentication it appears that a number of form submissions to the client's domain are going astray. Please advise.

**Comment by axllent** [comment]
It uses the default SilverStripe configured mailer. If you need SMTP authentication etc then your need to configure that instead. See https://docs.silverstripe.org/en/4/developer_guides/email/

**Comment by mhenden** [comment]
Thanks Ralph, was hoping this would be the case! 

cheers
mike





	14 Brees Street, Lower Hutt, Wellington, New Zealand
p: 04-577 0243, m: 027 4419 273, e: mike@mhdesign.co.nz <mailto:mike@mhdesign.co.nz>
w: www.mhdesign.co.nz <http://www.mhdesign.co.nz/>
